# --- APPLICATIONS BLUR & OPACITY ---
windowrule = match:tag ^multimedia_video.*$, no_blur True
windowrule = match:tag ^multimedia_video.*$, opacity 1.0 override

windowrule = match:tag ^settings.*$, opacity 0.8
windowrule = match:class ^(gedit|org.gnome.TextEditor|mousepad)$, opacity 0.9
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, opacity 0.9
windowrule = match:class ^(kitty)$, opacity 0.9

windowrule = match:class ^(discord|vesktop|org.telegram.desktop)$, opacity 1 1 1.0 override

layerrule = match:namespace ^(waybar)$, blur off
layerrule = match:namespace ^(waybar)$, ignore_alpha 0.5
layerrule = match:namespace ^(logout_dialog)$, blur off

# SwayNC
layerrule = match:namespace ^(swaync-control-center|swaync-notification-window)$, blur on
layerrule = match:namespace ^(swaync-control-center|swaync-notification-window)$, ignore_alpha 0
layerrule = match:namespace ^(swaync-control-center|swaync-notification-window)$, ignore_alpha 0.5
layerrule = match:namespace ^(swaync-control-center|swaync-notification-window)$, xray 0

# --- FLOAT & SIZE ---
windowrule = match:tag ^settings.*$, float on
windowrule = match:tag ^viewer.*$, float on

windowrule = match:tag ^multimedia_video.*$, float on
windowrule = match:tag ^multimedia_video.*$, size 900 506

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 50% 60%

windowrule {
    name = suppress-maximize-events
    match:class = .* 
    suppress_event = maximize
}
windowrule = float on, match:class ^$, match:title ^$, match:xwayland 1

# --- POP UPS AND DIALOGUES ---
windowrule = match:title ^(Сохранить как|Сохранить файл|Выбрать файл)$, float on
windowrule = match:title ^(Сохранить как|Сохранить файл|Выбрать файл)$, size 50% 60%
windowrule = match:title ^(Сохранить как|Сохранить файл|Выбрать файл)$, center on

windowrule = match:title ^(Открыть файл|Открыть папку)$, float on
windowrule = match:title ^(Открыть файл|Открыть папку)$, size 70% 60%
windowrule = float on, match:class ^(thunar)$, match:title negative:^.*(Thunar)$


# Steam
windowrule = float on, match:class ^(steam)$, match:title negative:^(Steam)$
