# --- APPLICATIONS BLUR & OPACITY ---

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, opacity 0.9
windowrule = match:class ^(foot)$, opacity 0.8


# --- FLOAT & SIZE ---

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 50% 60%

# Steam
windowrule = float on, match:class ^(steam)$, match:title negative:^(Steam)$

# Firefox
windowrule = tile on, match:class ^(firefox)$

windowrule = float on, match:class ^(firefox)$, match:title ^(About Mozilla Firefox)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Библиотека)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Удалить историю)$

windowrule = float on, pin on, size 560 340, match:title ^(Картинка в картинке)$

windowrule = float on, match:class ^(firefox)$, match:title negative:^.*(Mozilla Firefox)$

#AmneziaVPN
windowrule = center on, match:class ^(AmneziaVPN)$

#Happ
windowrule = float on, center on, match:class ^(Happ)$

#Thunar
windowrule = float on, size 1100 690, center on, match:class ^(thunar)$
windowrule = float on, match:class ^(thunar)$, match:title negative:^.*(Thunar)$

#Viemnior
windowrule = float on, center on, size 900 600, match:class ^(viewnior)$

#Mpv and vlc
windowrule = float on, center on, size 900 600, match:class ^(mpv|vlc)$

windowrule {
    name = suppress-maximize-events
    match:class = .* 
    suppress_event = maximize
}

windowrule = float on, match:class ^$, match:title ^$, match:xwayland 1

# --- POP UPS AND DIALOGUES ---
windowrule = match:title ^(Сохранить как|Сохранить файл|Выбрать файл|Выберите файл\(ы\))$, float on
windowrule = match:title ^(Сохранить как|Сохранить файл|Выбрать файл|Выберите файл\(ы\))$, size 1100 690
windowrule = match:title ^(Сохранить как|Сохранить файл|Выбрать файл|Выберите файл\(ы\))$, center on

windowrule = match:title ^(Открыть файл|Открыть папку)$, float on
windowrule = match:title ^(Открыть файл|Открыть папку)$, size 1100 690

