color0 #131314
color1 #ffb4ab
color2 #b6cad3
color3 #c1c7cc
color4 #d0c1d7
color5 #b6cad3
color6 #c1c7cc
color7 #e4e2e2
color8 #8d9194
color9 #ffb4ab
color10 #b6cad3
color11 #c1c7cc
color12 #d0c1d7
color13 #b6cad3
color14 #c1c7cc
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #131314
background            #131314
foreground            #e4e2e2
selection_foreground  #c3c7ca
selection_background  #42474a
active_border_color   #b6cad3
inactive_border_color #42474a
url_color             #b6cad3

active_tab_foreground   #21333b
active_tab_background   #b6cad3
inactive_tab_foreground #c3c7ca
inactive_tab_background #42474a
cursor_trail_color      #c3c7ca
